### ISSUE TITLE
Edit website to switch Keybase to Discord

### ISSUE THREAD

**Issue by misher2** [Chia-Network/chips#73]
At https://www.chia.net/2022/02/14/chia-improvement-proposals/

Change:
"Next you’ll need to make sure your idea is viable by vetting it in the #dev channel of our [Keybase](https://keybase.io/team/chia_network.public) forum."

To:
"Next you’ll need to make sure your idea is viable by vetting it in the #chia-development channel in our discord server. https://discord.gg/chia"

**Comment by danieljperry** [comment]
Thanks, I'll pass this on to get the website updated.
